apiVersion: v1
kind: Namespace
metadata:
  name: matrix-stack
  labels:
    app.kubernetes.io/name: matrix-stack
    app.kubernetes.io/part-of: enterprise-matrix-stack
---
# Optional: separate namespace for monitoring
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: matrix-stack-monitoring
